### ISSUE TITLE
Open project root directory instead ?

### ISSUE THREAD

**Issue by bbuccianti** [fasheng/dired-toggle#2]
There is a way of open the directory of the project instead of the current directory in which the file exists?

**Comment by fasheng** [comment]
I see, this is a good idea, but dired-toggle just try to keep lightweight. You could use [dired-sidebar](https://github.com/jojojames/dired-sidebar) instead, if you are not adapted to dired-sidebar, I will consider to implement this feature here~

**Comment by bbuccianti** [comment]
I use a lot project-find-file. Is builtin on emacs and you can search for files on the project. I don't how that works, but I think that we can use some similar function to get the project directory.

**Comment by fasheng** [comment]
Thanks for your quick advice, I will try to learn if project-find-file could fix this later.

**Comment by bbuccianti** [comment]
I'm glad to help! I'm a computer science student and we like to get involved with the development of the tools that I use.

Thank you so much for this package. If I can help you in any way, please tell me.

**Comment by fasheng** [comment]
Thanks, I append a commit just now, you could help to test it. Any feedback is welcome, enjoy!

You could use `C-u dired-toggle` or `dired-toggle-project-root` directly to toggle the project root directory.

**Comment by bbuccianti** [comment]
Works!

Thank you fasheng!
