### ISSUE TITLE
Toggle on different path

### ISSUE THREAD

**Issue by bbuccianti** [fasheng/dired-toggle#3]
Hi fasheng!

It's me again. Now I have a problem and want to know what do you think about it. 

Suppose that I have the following directories and files.

>    Folder A/file2
>    Folder B/file3
>    FolderB/Folder C/file5

If I'm editing file2 and I call dired-toggle it opens in folder A/. Great. But now i decided to navigate in this *Dired Toggle* buffer to Folder C/ with subtrees and I press 'o' to open the file5. And here is the trouble. If now I want to call dired-toggle to close the *Dired Toggle* buffer, it opens a new *Dired Toggle* buffer and renames the last one.

I hope you can understand. I think is trivial to check if a *Dired Toggle* buffer is open and close it. But maybe you can think better and I will be grateful if you explain it to me.

Thanks!!

**Comment by fasheng** [comment]
Thanks for your detailed report. Try to fix it now, please test again~

**Comment by bbuccianti** [comment]
Now when I invoke dired-toggle it shows 

dired-toggle--get-window: Symbol’s function definition is void: return

**Comment by fasheng** [comment]
How about this time?

**Comment by bbuccianti** [comment]
Now is working great!!! Thanks fasheng!!
